remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
include:
  - docs/
header_pages:
  - index.html
author: Vincent Giraud
twitter_username: vincentgiraud
github_username:  vincentgiraud
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
